# Name service
spring:
  application:
    name: service-two

# Port service
server:
  port: 8100

# Configure eureka server
eureka:

  #    Itself is both a client and a server. it must configure a property client
  client:

    #    Inform the server that it only is server and in the future it won't be a client eureka
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    info:
      enabled: true
    health:
      show-details: always
info:
  app:
    name: @project.name@
    description: @project.description@
    encoding: @project.build.sourceEncoding@
  java:
    version: @java.version@
